#!/usr/bin/env bash
# Installs and configures HAProxy

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8.\*

# Enabling init script
echo "ENABLED=1" > /etc/default/haproxy

# Creating a copy of HAProxy's config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# configuring to load balance web1 and web2 servers
echo "
	frontend myfrontend
		bind *:80
		option http-server-close
		option httplog
		option forwardfor
		default_backend mybackend
	backend mybackend
		mode http
		balance roundrobin
		server 69177-web-01 100.25.162.172:80 check
		server 69177-web-02 35.153.79.82:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
