#!/usr/bin/env bash
# Installs and configures HAProxy

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
apt-get install -y haproxy=2.8.\*

# Enabling init script
echo "ENABLED=1" > /etc/default/haproxy

# Creating a copy of HAProxy's config file
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

# configuring to load balance web1 and web2 servers
echo "
	bind *:80
	mode http
	balance roundrobin
	server 69177-web-01 100.25.162.172:80 check
	server 69177-web-02 35.153.79.82:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
